import ExcelJS from "exceljs";
import fs from "fs";
import path from "path";
import { isTemplateScaffolding } from "../src/understanding/classifyColumns";

/**
 * Regenerates src/templates/masterTemplates.ts from the bundled Apptio master
 * workbooks.
 *
 * The master workbooks are the *target* schema — the shape data must be in once
 * it is inside Apptio — not customer input. A customer hands over raw source
 * data; the job is to map that onto these columns and report how much of the
 * template was satisfied. Only the headers matter, never the rows.
 *
 * Run after replacing a workbook in packages/langgraph/data/:
 *   npx ts-node packages/langgraph/scripts/generateMasterTemplates.ts
 */

const DATA_DIR = path.join(__dirname, "..", "data");
const OUT = path.join(__dirname, "..", "src", "templates", "masterTemplates.ts");

// File name -> the master data type it defines. Explicit rather than derived,
// because the file names carry export dates that will change.
const MASTER_TYPES: [RegExp, string][] = [
  [/^All_Business_Services/i, "Business Services"],
  [/^Applications_Master_Data/i, "Applications"],
  [/^Chart_of_Accounts_Master_Data/i, "Chart of Accounts"],
  [/^Cloud_Service_Provider_Master_Data/i, "Cloud Service Providers"],
  [/^Cost_Source_Master_Data/i, "Cost Source"],
  [/^Data_Centers_Master_Data/i, "Data Centers"],
  [/^End_User_Devices_Master_Data/i, "End User Devices"],
  [/^Fixed_Asset_Master_Data/i, "Fixed Assets"],
  [/^IT_Resource_Towers_Master_Data/i, "IT Resource Towers"],
  [/^Labor_Master_Data/i, "Labor"],
  [/^Mainframes_Master_Data/i, "Mainframes"],
  [/^Network_Devices_Master_Data/i, "Network Devices"],
  [/^Projects_Master_Data/i, "Projects"],
  [/^Servers_Master_Data/i, "Servers"],
  [/^Storage_Devices_Master_Data/i, "Storage Devices"],
  [/^Storage_Master_Data/i, "Storage"],
  [/^Tickets_Master_Data/i, "Tickets"],
  [/^Vendor_Master_Data/i, "Vendors"],
];

function masterTypeFor(fileName: string): string | null {
  return MASTER_TYPES.find(([pattern]) => pattern.test(fileName))?.[1] ?? null;
}


async function readHeaderRow(filePath: string): Promise<string[]> {
  const reader = new ExcelJS.stream.xlsx.WorkbookReader(filePath, {
    worksheets: "emit",
    sharedStrings: "cache",
    entries: "emit",
    styles: "ignore",
  });
  for await (const worksheet of reader as any) {
    for await (const row of worksheet) {
      const headers = (row.values as any[])
        .slice(1)
        .map((v) => String(v?.text ?? v ?? "").trim())
        .filter((h) => h && h !== "undefined");
      return headers;
    }
  }
  return [];
}

async function main() {
  const files = fs
    .readdirSync(DATA_DIR)
    .filter((f) => /\.xlsx?$/i.test(f) && !f.startsWith("TBM-Taxonomy"))
    .sort();

  const templates: { masterType: string; fileName: string; expected: string[]; internal: string[] }[] = [];

  for (const fileName of files) {
    const masterType = masterTypeFor(fileName);
    if (!masterType) {
      console.log(`  skipped (no master type): ${fileName}`);
      continue;
    }
    // Streaming reader, stopping at row 1: only the headers matter, and
    // Cloud_Service_Provider alone is ~94k rows — loading whole workbooks to
    // read one row exhausts the heap.
    const headers = await readHeaderRow(path.join(DATA_DIR, fileName));

    const expected = headers.filter((h) => !isTemplateScaffolding(h));
    const internal = headers.filter((h) => isTemplateScaffolding(h));
    templates.push({ masterType, fileName, expected, internal });
    console.log(`  ${masterType.padEnd(24)} ${expected.length} expected + ${internal.length} internal`);
  }

  templates.sort((a, b) => a.masterType.localeCompare(b.masterType));

  const body = templates
    .map(
      (t) => `  {
    masterType: ${JSON.stringify(t.masterType)},
    sourceWorkbook: ${JSON.stringify(t.fileName)},
    expectedColumns: [
${t.expected.map((c) => `      ${JSON.stringify(c)},`).join("\n")}
    ],
    internalColumns: [
${t.internal.map((c) => `      ${JSON.stringify(c)},`).join("\n")}
    ],
  },`
    )
    .join("\n");

  fs.writeFileSync(
    OUT,
    `// GENERATED by scripts/generateMasterTemplates.ts — do not edit by hand.
//
// The Apptio master workbooks are the target schema, not customer input. Each
// entry lists the columns a customer's source data must ultimately satisfy.
//
// expectedColumns  business columns the customer can actually supply — the
//                  denominator for column-coverage reporting.
// internalColumns  Apptio-generated scaffolding (join keys, metafields,
//                  benchmark and QA helper columns). A customer cannot provide
//                  these; counting them would make every coverage figure wrong.

export interface MasterTemplate {
  masterType: string;
  sourceWorkbook: string;
  expectedColumns: string[];
  internalColumns: string[];
}

export const MASTER_TEMPLATES: MasterTemplate[] = [
${body}
];

export function findMasterTemplate(masterType: string): MasterTemplate | undefined {
  return MASTER_TEMPLATES.find((t) => t.masterType.toLowerCase() === masterType.toLowerCase());
}
`,
    "utf-8"
  );
  console.log(`\nwrote ${OUT} (${templates.length} templates)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
